---
project_name: gdscript-example-project
loglevel: info
analyses:
- analysis_name: gd check
  source_directory: /Users/user1/emerge/project/source
  only_permit_languages:
  - gdscript
  only_permit_file_extensions:
  - .gd
  ignore_directories_containing:
  - __pycache__
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - louvain_modularity
  - fan_in_out
  - tfidf
  export:
  - directory: /Users/user1/emerge/project/export
  - graphml
  - json
  - tabular_file
  - tabular_console_overall
  - d3
